import type BsAccordion from './components/bs-accordion';
import type BsAlert from './components/bs-alert';
import type BsButton from './components/bs-button';
import type BsButtonGroup from './components/bs-button-group';
import type BsCarousel from './components/bs-carousel';
import type BsCollapse from './components/bs-collapse';
import type BsContextualHelp from './components/bs-contextual-help';
import type BsDropdown from './components/bs-dropdown';
import type BsForm from './components/bs-form';
import type BsLinkTo from './components/bs-link-to';
import type BsListGroup from './components/bs-list-group';
import type BsModal from './components/bs-modal';
import type BsModalSimple from './components/bs-modal-simple';
import type BsNav from './components/bs-nav';
import type BsNavbar from './components/bs-navbar';
import type BsPopover from './components/bs-popover';
import type BsProgress from './components/bs-progress';
import type BsSpinner from './components/bs-spinner';
import type BsTab from './components/bs-tab';
import type BsTooltip from './components/bs-tooltip';

export default interface EmberBootstrapRegistry {
  BsAccordion: typeof BsAccordion;
  'bs-accordion': typeof BsAccordion;
  BsAlert: typeof BsAlert;
  'bs-alert': typeof BsAlert;
  BsButton: typeof BsButton;
  'bs-button': typeof BsButton;
  BsButtonGroup: typeof BsButtonGroup;
  'bs-button-group': typeof BsButtonGroup;
  BsCarousel: typeof BsCarousel;
  'bs-carousel': typeof BsCarousel;
  BsCollapse: typeof BsCollapse;
  'bs-collapse': typeof BsCollapse;
  BsContextualHelp: typeof BsContextualHelp;
  'bs-contextual-help': typeof BsContextualHelp;
  BsDropdown: typeof BsDropdown;
  'bs-dropdown': typeof BsDropdown;
  BsForm: typeof BsForm;
  'bs-form': typeof BsForm;
  BsLinkTo: typeof BsLinkTo;
  'bs-link-to': typeof BsLinkTo;
  BsListGroup: typeof BsListGroup;
  'bs-list-group': typeof BsListGroup;
  BsModal: typeof BsModal;
  'bs-modal': typeof BsModal;
  BsModalSimple: typeof BsModalSimple;
  'bs-modal-simple': typeof BsModalSimple;
  BsNav: typeof BsNav;
  'bs-nav': typeof BsNav;
  BsNavbar: typeof BsNavbar;
  'bs-navbar': typeof BsNavbar;
  BsPopover: typeof BsPopover;
  'bs-popover': typeof BsPopover;
  BsProgress: typeof BsProgress;
  'bs-progress': typeof BsProgress;
  BsSpinner: typeof BsSpinner;
  'bs-spinner': typeof BsSpinner;
  BsTab: typeof BsTab;
  'bs-tab': typeof BsTab;
  BsTooltip: typeof BsTooltip;
  'bs-tooltip': typeof BsTooltip;
}
