YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "Components.Accordion",
        "Components.AccordionItem",
        "Components.Alert",
        "Components.Button",
        "Components.ButtonGroup",
        "Components.ButtonGroupButton",
        "Components.Collapse",
        "Components.ContextualHelp",
        "Components.Dropdown",
        "Components.DropdownButton",
        "Components.DropdownMenu",
        "Components.DropdownMenuItem",
        "Components.DropdownToggle",
        "Components.Form",
        "Components.FormElement",
        "Components.FormGroup",
        "Components.Modal",
        "Components.ModalBody",
        "Components.ModalDialog",
        "Components.ModalFooter",
        "Components.ModalHeader",
        "Components.ModalSimple",
        "Components.Nav",
        "Components.NavItem",
        "Components.NavLink",
        "Components.Navbar",
        "Components.NavbarContent",
        "Components.NavbarNav",
        "Components.NavbarToggle",
        "Components.Popover",
        "Components.PopoverElement",
        "Components.Progress",
        "Components.ProgressBar",
        "Components.Tab",
        "Components.TabPane",
        "Components.Tooltip",
        "Components.TooltipElement",
        "Mixins.ComponentChild",
        "Mixins.ComponentParent",
        "Mixins.DropdownToggle",
        "Mixins.SizeClass",
        "Mixins.SubComponent",
        "Mixins.TransitionSupport",
        "Mixins.TypeClass"
    ],
    "modules": [],
    "allModules": [],
    "elements": []
} };
});